version: "3"

services:
  app.server:
    build: .
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Denver"
    links:
      - mysql.server
      - email.server
      - redis.server
    volumes:
      - log-volume:/var/log

  mysql.server:
    image: mysql:8.0.21
    restart: always
    expose:
      - 5001
    ports:
      - 5001:3306
    environment:
      TZ: "America/Denver"
      MYSQL_ROOT_PASSWORD: "siga"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - mysql-volume:/var/lib/mysql

  redis.server:
    image: redis:alpine
    expose:
      - 5002
    ports:
      - 5002:6379
  
  email.server:
    image: schickling/mailcatcher
    restart: always
    expose:
      - 5003
    ports:
      - 5003:1080
      - 1025:1025

volumes:
  log-volume: {}
  mysql-volume: {}
